//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uniqlo_project.Resources.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("uniqlo_project.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string AutologinDescription {
            get {
                return ResourceManager.GetString("AutologinDescription", resourceCulture);
            }
        }
        
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string SelectGenderTitle {
            get {
                return ResourceManager.GetString("SelectGenderTitle", resourceCulture);
            }
        }
        
        internal static string PromoCodePlaceholder {
            get {
                return ResourceManager.GetString("PromoCodePlaceholder", resourceCulture);
            }
        }
        
        internal static string RegValidationDescription {
            get {
                return ResourceManager.GetString("RegValidationDescription", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        internal static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        internal static string RequiredFirstName {
            get {
                return ResourceManager.GetString("RequiredFirstName", resourceCulture);
            }
        }
        
        internal static string InvalidNameAlert {
            get {
                return ResourceManager.GetString("InvalidNameAlert", resourceCulture);
            }
        }
        
        internal static string InvalidFirstNameAlert {
            get {
                return ResourceManager.GetString("InvalidFirstNameAlert", resourceCulture);
            }
        }
        
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        internal static string InvalidEmailAlert {
            get {
                return ResourceManager.GetString("InvalidEmailAlert", resourceCulture);
            }
        }
        
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        internal static string ResultsTitle {
            get {
                return ResourceManager.GetString("ResultsTitle", resourceCulture);
            }
        }
        
        internal static string DailyMeasurements {
            get {
                return ResourceManager.GetString("DailyMeasurements", resourceCulture);
            }
        }
        
        internal static string MenuForDay {
            get {
                return ResourceManager.GetString("MenuForDay", resourceCulture);
            }
        }
        
        internal static string Workout {
            get {
                return ResourceManager.GetString("Workout", resourceCulture);
            }
        }
        
        internal static string MarathonChat {
            get {
                return ResourceManager.GetString("MarathonChat", resourceCulture);
            }
        }
        
        internal static string UserProfileTitle {
            get {
                return ResourceManager.GetString("UserProfileTitle", resourceCulture);
            }
        }
        
        internal static string ProfileSectionTitle {
            get {
                return ResourceManager.GetString("ProfileSectionTitle", resourceCulture);
            }
        }
        
        internal static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        internal static string PersonalDataSectionTitle {
            get {
                return ResourceManager.GetString("PersonalDataSectionTitle", resourceCulture);
            }
        }
        
        internal static string YourNameTitle {
            get {
                return ResourceManager.GetString("YourNameTitle", resourceCulture);
            }
        }
        
        internal static string GenderTitle {
            get {
                return ResourceManager.GetString("GenderTitle", resourceCulture);
            }
        }
        
        internal static string BirthDateTitle {
            get {
                return ResourceManager.GetString("BirthDateTitle", resourceCulture);
            }
        }
        
        internal static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        internal static string ChangePassTitle {
            get {
                return ResourceManager.GetString("ChangePassTitle", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string EmergencyCall {
            get {
                return ResourceManager.GetString("EmergencyCall", resourceCulture);
            }
        }
        
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        internal static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string AlertNotFilled {
            get {
                return ResourceManager.GetString("AlertNotFilled", resourceCulture);
            }
        }
        
        internal static string ProfileTab {
            get {
                return ResourceManager.GetString("ProfileTab", resourceCulture);
            }
        }
        
        internal static string MarathonTab {
            get {
                return ResourceManager.GetString("MarathonTab", resourceCulture);
            }
        }
        
        internal static string ResultsTab {
            get {
                return ResourceManager.GetString("ResultsTab", resourceCulture);
            }
        }
        
        internal static string MenuTab {
            get {
                return ResourceManager.GetString("MenuTab", resourceCulture);
            }
        }
        
        internal static string ExecTab {
            get {
                return ResourceManager.GetString("ExecTab", resourceCulture);
            }
        }
        
        internal static string ChatTab {
            get {
                return ResourceManager.GetString("ChatTab", resourceCulture);
            }
        }
        
        internal static string ChooseMarathonTitle {
            get {
                return ResourceManager.GetString("ChooseMarathonTitle", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
    }
}
